<a href="https://colab.research.google.com/github/gundaminpde/2022/blob/main/2nd_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
sample=[5,24,5,'ddd']

print(sample)

print(type(sample))

print(sample[0])

print(sample[2:])
print(sample[:3])

print(sample[-1])
print(sample[-2])

print(len(sample))


[5, 24, 5, 'ddd']
<class 'list'>
5
[5, 'ddd']
[5, 24, 5]
ddd
5
4


In [24]:
basket = ['a','aa','aaa']

for x in basket:
  print(x,", a가 모두" ,len(x),"개")

a , a가 모두 1 개
aa , a가 모두 2 개
aaa , a가 모두 3 개


In [25]:
## 행렬

import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

X = np.array([[1],[4],[7]])

print(A)
print(X)
print(len(A))
print("행렬크기", np.shape(X))

print('행렬곱 AX = ', A@X)

print('matmul 사용',np.matmul(A, X), sep ='\n')





[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]
3
행렬크기 (3, 1)
행렬곱 AX =  [[ 30]
 [ 66]
 [102]]
matmul 사용
[[ 30]
 [ 66]
 [102]]


In [33]:
## 행렬

import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
X = np.array([[1],[4],[7]])
Y = np.array([[2,3,5],[1,0,1],[-1,3,5]])

print("행렬 A 크기 =", np.shape(A))
print("행렬 Y 크기 =", np.shape(Y))
print("행렬 X 크기 =", np.shape(X))
print("행렬 A =", A, sep='\n')
print("행렬 Y =", Y, sep='\n')
print("행렬 X =", X, sep='\n')

print('A+Y =',A+Y, sep='\n')
print('A*Y =',A*Y, sep='\n')

print('A+X =',A+Y, sep='\n') # Numpy Broadcasting
print('A*X =',A*Y, sep='\n')

행렬 A 크기 = (3, 3)
행렬 Y 크기 = (3, 3)
행렬 X 크기 = (3, 1)
행렬 A =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
행렬 Y =
[[ 2  3  5]
 [ 1  0  1]
 [-1  3  5]]
행렬 X =
[[1]
 [4]
 [7]]
A+Y =
[[ 3  5  8]
 [ 5  5  7]
 [ 6 11 14]]
A*Y =
[[ 2  6 15]
 [ 4  0  6]
 [-7 24 45]]
A+X =
[[ 3  5  8]
 [ 5  5  7]
 [ 6 11 14]]
A*X =
[[ 2  6 15]
 [ 4  0  6]
 [-7 24 45]]


In [39]:
aaa=tuple()
aaa=1,2,3,4
print(aaa)
aaa=5,6,7,8
print(aaa)
aaa[2]=100


(1, 2, 3, 4)
(5, 6, 7, 8)


TypeError: ignored

In [1]:
## 리스트도 가능

bbb=[1,2,3,4]
x,y,z,w,l = bbb 
x

ValueError: ignored

In [4]:
# 진짜 공집합 만들기

empty_set = set()
empty_set

set()

In [9]:
A_set = {'aaaabbbcccc'}

print(A_set)

Another_set =set('aaaabbbcccc')

Another_set

{'aaaabbbcccc'}


{'a', 'b', 'c'}