<a href="https://colab.research.google.com/github/gundaminpde/2022/blob/main/2nd_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
sample=[5,24,5,'ddd']

print(sample)

print(type(sample))

print(sample[0])

print(sample[2:])
print(sample[:3])

print(sample[-1])
print(sample[-2])

print(len(sample))


[5, 24, 5, 'ddd']
<class 'list'>
5
[5, 'ddd']
[5, 24, 5]
ddd
5
4


In [27]:
basket = ['a','aa','aaa']

for x in basket:
  print(x,", a가 모두" ,len(x),"개")
  for y in basket:
    print(x,'와',y, ',a가 모두', len(x)+len(y))

a , a가 모두 1 개
a 와 a ,a가 모두 2
a 와 aa ,a가 모두 3
a 와 aaa ,a가 모두 4
aa , a가 모두 2 개
aa 와 a ,a가 모두 3
aa 와 aa ,a가 모두 4
aa 와 aaa ,a가 모두 5
aaa , a가 모두 3 개
aaa 와 a ,a가 모두 4
aaa 와 aa ,a가 모두 5
aaa 와 aaa ,a가 모두 6


In [33]:
s = 'DaDsasdfAAAghj'

print(s[0])
print(s[3])
print(s[-3])

changed_s=str()

for x in s:
  if x.islower():
    changed_s+=x.upper()
  else:
    changed_s+=x.lower()

print(changed_s)

print(s)

print(s.swapcase())

D
s
g
dAdSASDFaaaGHJ
DaDsasdfAAAghj
dAdSASDFaaaGHJ


In [34]:
aaa=input("알파벳만 입력해라.")


if not aaa.isalpha():
    print("내 말 좀 들어라")
else:
    print("잘했어.")


알파벳만 입력해라.123
내 말 좀 들어라


In [44]:
## 우영우, 역삼역 같은 대칭문 확인하기

txt= input("입력해보시라. \n")

modified_1 = txt.replace(' ','')

reversed_1=str()

indx=len(modified_1)-1

while indx >=0:
  reversed_1 +=modified_1[indx]
  ##print(reversed_1)
  indx -= 1

if modified_1 == reversed_1:
  print("이것은 대칭문")
else:
  print("대칭문이 아니다.")

입력해보시라. 
살모사
대칭문이 아니다.


In [52]:
aaa=[12,6,3,4,5,34,6,6,5]

print(aaa[1:5])

aaa.append(20)
print(aaa)

aaa+=[30]
print(aaa)

bbb=aaa
print(bbb)

del bbb[2:8]
print(bbb)
print(aaa)

aaa=aaa+[2,3]
print(aaa)

[6, 3, 4, 5]
[12, 6, 3, 4, 5, 34, 6, 6, 5, 20]
[12, 6, 3, 4, 5, 34, 6, 6, 5, 20, 30]
[12, 6, 3, 4, 5, 34, 6, 6, 5, 20, 30]
[12, 6, 5, 20, 30]
[12, 6, 5, 20, 30]
[12, 6, 5, 20, 30, 2, 3]


In [59]:
ccc= [[1,2,3],[2,2,3],[1,1]]

print(ccc)


threeby3= [[1,2,3],[2,2,3],[1,1,2]]

print(threeby3)

ccc[1][0]

empty=[]

empty2=list()

print(empty)
print(empty2)


[[1, 2, 3], [2, 2, 3], [1, 1]]
[[1, 2, 3], [2, 2, 3], [1, 1, 2]]
[]
[]


In [61]:
## 행렬

import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

X = np.array([[1],[4],[7]])

print(A)
print(X)
print(len(A))
print("행렬크기", np.shape(X))

print('행렬곱 AX = ', A@X)

print('matmul 사용',np.matmul(A, X), sep ='\n')

print('dot 사용',np.dot(A, X), sep ='\n')
print(A+X)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]
3
행렬크기 (3, 1)
행렬곱 AX =  [[ 30]
 [ 66]
 [102]]
matmul 사용
[[ 30]
 [ 66]
 [102]]
dot 사용
[[ 30]
 [ 66]
 [102]]
[[ 2  3  4]
 [ 8  9 10]
 [14 15 16]]


In [33]:
## 행렬

import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
X = np.array([[1],[4],[7]])
Y = np.array([[2,3,5],[1,0,1],[-1,3,5]])

print("행렬 A 크기 =", np.shape(A))
print("행렬 Y 크기 =", np.shape(Y))
print("행렬 X 크기 =", np.shape(X))
print("행렬 A =", A, sep='\n')
print("행렬 Y =", Y, sep='\n')
print("행렬 X =", X, sep='\n')

print('A+Y =',A+Y, sep='\n')
print('A*Y =',A*Y, sep='\n')

print('A+X =',A+Y, sep='\n') # Numpy Broadcasting
print('A*X =',A*Y, sep='\n')

행렬 A 크기 = (3, 3)
행렬 Y 크기 = (3, 3)
행렬 X 크기 = (3, 1)
행렬 A =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
행렬 Y =
[[ 2  3  5]
 [ 1  0  1]
 [-1  3  5]]
행렬 X =
[[1]
 [4]
 [7]]
A+Y =
[[ 3  5  8]
 [ 5  5  7]
 [ 6 11 14]]
A*Y =
[[ 2  6 15]
 [ 4  0  6]
 [-7 24 45]]
A+X =
[[ 3  5  8]
 [ 5  5  7]
 [ 6 11 14]]
A*X =
[[ 2  6 15]
 [ 4  0  6]
 [-7 24 45]]


In [62]:
aaa=tuple()
aaa=1,2,3,4
print(aaa)
aaa=5,6,7,8
print(aaa)
bbb=()
print(bbb)
aaa[2]=100


(1, 2, 3, 4)
(5, 6, 7, 8)
()


TypeError: ignored

In [64]:
## string도 마찬가지

prince='바다의 왕자 박명수'

print(prince[2])

print[2]='에'

의


TypeError: ignored

In [68]:
### unpacking

aaa = '바', '다', '에', '왕', '자'
q,w,r,t,y=aaa
print(w)

## 리스트도 가능

bbb=[1,2,3,4]
x,y,z,w = bbb 
print(x)

## x,y,z,w,l = bbb 

다
1


In [ ]:
# 진짜 공집합 만들기

empty_set = set()
empty_set

In [79]:
A_set = {'aaaabbbcccc'}

print(A_set)

Another_set =set('aaaabbbcccc')

print(Another_set)

print('b' in Another_set)

other_set=set("weshyijkxfcgv")

print(Another_set | other_set)

print(Another_set & other_set)

print(Another_set ^ other_set)

thing1 = {}
print(type(thing1))

thing2 = set()
print(type(thing2))

{'aaaabbbcccc'}
{'a', 'c', 'b'}
True
{'b', 'e', 'i', 's', 'k', 'x', 'v', 'g', 'y', 'a', 'j', 'c', 'w', 'f', 'h'}
{'c'}
{'e', 'i', 's', 'k', 'b', 'x', 'a', 'j', 'v', 'g', 'w', 'f', 'y', 'h'}
<class 'dict'>
<class 'set'>


In [83]:
### Dictionary 

Ex_dic = {"영어":10, "수학":20, "국어":'F'}

print(type(Ex_dic))

print(Ex_dic["수학"])

print(len(Ex_dic))

print(Ex_dic.keys())

print(Ex_dic.values())

print('국어' in Ex_dic)

print('체육' in Ex_dic)


<class 'dict'>
20
3
dict_keys(['영어', '수학', '국어'])
dict_values([10, 20, 'F'])
True
False
